name: pomo
description: "O seu app de estudos com foco e produtividade."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  figma: ^7.1.1
  flutter_svg: ^2.0.10+1
  image_picker: ^0.8.4+1
  fading_edge_scrollview: ^4.1.1
  http: ^1.2.2
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Cera Pro
      fonts:
      - asset: assets/fonts/CeraPro-Regular.ttf
      - asset: assets/fonts/CeraPro-Bold.ttf
        weight: 700
      - asset: assets/fonts/CeraPro-Light.ttf
        weight: 300
      - asset: assets/fonts/CeraPro-Medium.ttf
        weight: 500
      - asset: assets/fonts/CeraPro-Black.ttf
        weight: 900
      - asset: assets/fonts/CeraPro-Thin.ttf
        weight: 100