// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS6rotUs0Zq7TOub84LdpYpKvP10Wgx0Y',
    appId: '1:86379459624:web:e1476c8a31d24d5e72311d',
    messagingSenderId: '86379459624',
    projectId: 'pomo-532bd',
    authDomain: 'pomo-532bd.firebaseapp.com',
    storageBucket: 'pomo-532bd.appspot.com',
    measurementId: 'G-B34W2SZ9G5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd3Hmp5AsaJMdI-6oMIffbOZ4pe_Yjbkc',
    appId: '1:86379459624:android:cb87be9f2def35ca72311d',
    messagingSenderId: '86379459624',
    projectId: 'pomo-532bd',
    storageBucket: 'pomo-532bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5Omy5JzIkGs2GfPPhJCkstzhRu9DY4dY',
    appId: '1:86379459624:ios:dc79d8f6ca5afc9072311d',
    messagingSenderId: '86379459624',
    projectId: 'pomo-532bd',
    storageBucket: 'pomo-532bd.appspot.com',
    iosBundleId: 'com.example.pomo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5Omy5JzIkGs2GfPPhJCkstzhRu9DY4dY',
    appId: '1:86379459624:ios:dc79d8f6ca5afc9072311d',
    messagingSenderId: '86379459624',
    projectId: 'pomo-532bd',
    storageBucket: 'pomo-532bd.appspot.com',
    iosBundleId: 'com.example.pomo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBS6rotUs0Zq7TOub84LdpYpKvP10Wgx0Y',
    appId: '1:86379459624:web:9d719e8cdf7023e472311d',
    messagingSenderId: '86379459624',
    projectId: 'pomo-532bd',
    authDomain: 'pomo-532bd.firebaseapp.com',
    storageBucket: 'pomo-532bd.appspot.com',
    measurementId: 'G-586L24LHVN',
  );
}